import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@styles/globals.css";
import { MainLayout } from "@components/common/layouts/main-layout";
import RootStyleRegistry from "./mantine";
import AppProgressBar from "@components/common/progress-bar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className} suppressHydrationWarning={true}>
        <RootStyleRegistry>
          <AppProgressBar>
            <MainLayout>{children}</MainLayout>
          </AppProgressBar>
        </RootStyleRegistry>
      </body>
    </html>
  );
}
